Pin xformers version to 0.0.35 since the current branch modified the API
This fixes this error when the latent image is decoded:

File "/opt/comfyui/comfy/ldm/modules/diffusionmodules/model.py", line 300, in xformers_attention out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'xformers.ops' has no attribute 'memory_efficient_attention'